/** 界面文案：简体 / 繁体（香港书面语用字，与 opencc cn→hk 一致） */

export type AppLocale = "zh-Hans" | "zh-Hant";

const zhHans = {
  appTitle: "理大音游人格测试设计",
  metaDescription:
    "理大音游人格测试：P/E、S/M、A/I、C/B 四维度，理大校园 × 音游主题问卷",
  indexSubtitle: "用这份人格问卷，更认识自己一点。",
  indexTakeTest: "开始测试",
  navHistory: "测试记录",
  footerMadeBy: "由",
  footerAnd: "与",
  footerBasedOn: "制作，改编自",
  footerWork: "的作品。",
  localeHans: "简体",
  localeHant: "繁體",
  localeSwitcherAria: "切换界面语言：简体或繁体",
  testSeeResult: "查看结果",
  testLoadingLayout: "正在加载题目与选项顺序……",
  testInstructions: "说明",
  testInstructionsAria: "打开测试说明",
  pageLoading: "加载中……",
  pageError: "出错了，请刷新页面后重试。",
  pageNoData: "暂无数据",
  resultDimensionRecap: "维度回顾",
  resultYourResult: "测试结果",
  resultTableCode: "编码",
  resultTableName: "名称",
  resultTableDesc: "描述",
  resultTableSoul: "对应的理大灵魂",
  resultArchetypeImageAlt: "{type} · {name} 人格结果图鉴",
  resultSurvivalTitle: "给你的理大生存建议",
  statsDimensionTitle: "维度得分",
  statsDimensionHint:
    "共 {count} 题计分 · 各轴百分比 = 该倾向题数 ÷ 与同对立组题数之和",
  statsRadarAria: "八维得分雷达图",
  radarSeriesName: "占比",
  historyTitle: "测试记录",
  tocTitle: "目录",
  lisaPreviewDocTitle: "彩蛋预览 · 理大音游人格测试设计",
  lisaPreviewIntro:
    "下方为解锁「今井莉莎限定评价」后在结果页中插入的区块样式预览（与真实解锁时一致）。",
  lisaEggBadge: "隐藏彩蛋 · 今井莉莎限定评价",
  lisaImageAlt: "今井莉莎（BanG Dream!）",
  instructionsHeading: "说明",
  instructionsStart: "开始测试",
  instructionsLine1:
    "请根据你的直觉选择 A 或 B。",
  instructionsItem1: "没有标准答案，按真实习惯选择即可。",
  instructionsItem2: "不要过度纠结措辞，第一印象往往更准。",
  instructionsItem3:
    "最后一题为社团征集说明，不计入人格结果，选完即可提交。",
  instructionsLeadHtml:
    "本测试题库专为<strong>理大音游人</strong>定制。题目将理大的校园生活场景（如红砖墙、Z-Core、创新楼等）与主流音游（PJSK、Arcaea、maimai 等）的语境结合，仅供娱乐与自我觉察。",
  dimP: "精度至上（P）",
  dimE: "表现至上（E）",
  dimS: "独行侠（S）",
  dimM: "社交达人（M）",
  dimA: "逻辑分析（A）",
  dimI: "肌肉直觉（I）",
  dimC: "持久稳定（C）",
  dimB: "瞬间爆发（B）",
  dimensionRecapPE: "P/E：精度至上 与 表现至上",
  dimensionRecapSM: "S/M：独行侠 与 社交达人",
  dimensionRecapAI: "A/I：逻辑分析 与 肌肉直觉",
  dimensionRecapCB: "C/B：持久稳定 与 瞬间爆发",
  spectrumFootnote:
    "这个系统涵盖了从「硬核技术宅」到「社交小蝴蝶」的所有光谱。",
  polyTrait: "特质：",
  polySurvival: "生存建议：",
  polyPitfall: "避坑：",
  polyClosingTitle: "测试卡片底部寄语：",
  polyIntroBefore: "下面是根据你的测试结果",
  polyIntroAfter:
    "定制的理大生存建议：既是音游向提示，也针对你在",
  polyIntroPolyu: "香港理工大学（PolyU）",
  polyIntroTail: "学习与生活里容易踩坑的地方。",
  guideTitleEmic: "EMIC 【理大向日葵 (莉莎型)】",
} as const;

const zhHant = {
  appTitle: "理大音遊人格測試設計",
  metaDescription:
    "理大音遊人格測試：P/E、S/M、A/I、C/B 四維度，理大校園 × 音遊主題問卷",
  indexSubtitle: "用這份人格問卷，更認識自己一點。",
  indexTakeTest: "開始測試",
  navHistory: "測試記錄",
  footerMadeBy: "由",
  footerAnd: "與",
  footerBasedOn: "製作，改編自",
  footerWork: "的作品。",
  localeHans: "简体",
  localeHant: "繁體",
  localeSwitcherAria: "切換介面語言：簡體或繁體",
  testSeeResult: "查看結果",
  testLoadingLayout: "正在載入題目與選項順序……",
  testInstructions: "說明",
  testInstructionsAria: "開啟測試說明",
  pageLoading: "載入中……",
  pageError: "發生錯誤，請重新整理頁面後再試。",
  pageNoData: "暫無資料",
  resultDimensionRecap: "維度回顧",
  resultYourResult: "測試結果",
  resultTableCode: "編碼",
  resultTableName: "名稱",
  resultTableDesc: "描述",
  resultTableSoul: "對應的理大靈魂",
  resultArchetypeImageAlt: "{type} · {name} 人格結果圖鑑",
  resultSurvivalTitle: "給你的理大生存建議",
  statsDimensionTitle: "維度得分",
  statsDimensionHint:
    "共 {count} 題計分 · 各軸百分比 = 該傾向題數 ÷ 與同對立組題數之和",
  statsRadarAria: "八維得分雷達圖",
  radarSeriesName: "佔比",
  historyTitle: "測試記錄",
  tocTitle: "目錄",
  lisaPreviewDocTitle: "彩蛋預覽 · 理大音遊人格測試設計",
  lisaPreviewIntro:
    "下方為解鎖「今井莉莎限定評價」後在結果頁中插入的區塊樣式預覽（與真實解鎖時一致）。",
  lisaEggBadge: "隱藏彩蛋 · 今井莉莎限定評價",
  lisaImageAlt: "今井莉莎（BanG Dream!）",
  instructionsHeading: "說明",
  instructionsStart: "開始測試",
  instructionsLine1: "請根據你的直覺選擇 A 或 B。",
  instructionsItem1: "沒有標準答案，按真實習慣選擇即可。",
  instructionsItem2: "不要過度糾結措辭，第一印象往往更準。",
  instructionsItem3:
    "最後一題為社團徵集說明，不計入人格結果，選完即可提交。",
  instructionsLeadHtml:
    "本測試題庫專為<strong>理大音遊人</strong>度身訂造。題目將理大的校園生活場景（如紅磚牆、Z-Core、創新樓等）與主流音遊（PJSK、Arcaea、maimai 等）的語境結合，僅供娛樂與自我覺察。",
  dimP: "精度至上（P）",
  dimE: "表現至上（E）",
  dimS: "獨行俠（S）",
  dimM: "社交達人（M）",
  dimA: "邏輯分析（A）",
  dimI: "肌肉直覺（I）",
  dimC: "持久穩定（C）",
  dimB: "瞬間爆發（B）",
  dimensionRecapPE: "P/E：精度至上 與 表現至上",
  dimensionRecapSM: "S/M：獨行俠 與 社交達人",
  dimensionRecapAI: "A/I：邏輯分析 與 肌肉直覺",
  dimensionRecapCB: "C/B：持久穩定 與 瞬間爆發",
  spectrumFootnote:
    "這個系統涵蓋了從「硬核技術宅」到「社交小蝴蝶」的所有光譜。",
  polyTrait: "特質：",
  polySurvival: "生存建議：",
  polyPitfall: "避坑：",
  polyClosingTitle: "測試卡片底部寄語：",
  polyIntroBefore: "下面是根據你的測試結果",
  polyIntroAfter:
    "度身訂造的理大生存建議：既是音遊向提示，也針對你在",
  polyIntroPolyu: "香港理工大學（PolyU）",
  polyIntroTail: "學習與生活裏容易踩坑的地方。",
  guideTitleEmic: "EMIC 【理大向日葵 (莉莎型)】",
} as const;

export type UiStringKey = keyof typeof zhHans;

export const UI_STRINGS: Record<AppLocale, Record<UiStringKey, string>> = {
  "zh-Hans": zhHans,
  "zh-Hant": zhHant,
};
